version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always

  locust:
    image: locustio/locust:latest
    container_name: locust
    volumes:
      - ./locust:/mnt/locust
    ports:
      - "8089:8089"
    command: >
      locust -f /mnt/locust/locustfile.py --master --host=http://master:8089
    restart: always

  worker:
    image: locustio/locust:latest
    container_name: locust_worker
    volumes:
      - ./locust:/mnt/locust
    command: >
      locust -f /mnt/locust/locustfile.py --worker --master-host=locust
    restart: always


volumes:
  prometheus_data: