global:
  scrape_interval: 1s
  evaluation_interval: 1s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # rules

scrape_configs:
  - job_name: "backend"

    static_configs:
      - targets: ["{BACKEND_IP}:5000"]